### ISSUE TITLE
crates.io package

### ISSUE THREAD

**Issue by riptl** [jgraef/worldclock#1]
This is super useful! Any chance you can pubilsh this on crates.io? 

EDIT: so you can do `cargo install worldclock`

**Comment by jgraef** [comment]
I'm planning on doing that. But some features I want are not implemented and the help output is not formatted how I want it.

 For now you can clone the repo and then install with: `cargo install --path .`

**Comment by jgraef** [comment]
I removed the not-finished features for now. They were:

 - Show times for a time specified as command line option instead of current time.
 - Keep watching time (can be achieved using `watch`)

Published to crates.io: https://crates.io/crates/worldclock
